### ISSUE TITLE
3D Transforms, IE 10, FireFox 10...

### ISSUE THREAD

**Issue by resistdesign** [boblemarin/Sprite3D.js#6]
I'm not seeing any 3D transform support in version 2 in IE 10 or FireFox 10, just in WebKit based browsers.

**Comment by boblemarin** [comment]
IE10 only has a limited support for 3D transforms, it does not allow nested transformed elements, so you can't build a hierarchy (i.e. a cube). The interest of the library is therefore quite limited for now in IE.

Speaking of Firefox, Sprite3D works in Firefox since version 16 (when they implemented 3D transforms). Are you sure you are talking about Firefox 10 ? (current version is 20)

**Comment by boblemarin** [comment]
Considering that IE 10 has no support for nested transforms, there is nothing I can do here, it's up to Microsoft to improve their browser.
And for Firefox, I didn't notice any problem, nor had any reports.
I'm closing the issue as I don't see anything else to do.
