### ISSUE TITLE
What is the actual version?

### ISSUE THREAD

**Issue by yckart** [boblemarin/Sprite3D.js#7]
In your [SyntaxDemo](http://sprite3d.minimal.be/SyntaxDemo/) you refer to a different source as in this repo.

In demo: http://sprite3d.minimal.be/SyntaxDemo/js/Sprite3D2.js
In repo: https://github.com/boblemarin/Sprite3D.js/blob/v2/Sprite3D.js

**Comment by boblemarin** [comment]
The current version is 2.0.2, available on the master branch here.
I'm currently doing some house cleaning and will close the old sites because it gets confusing. 
I must find the time to update some more demos and examples. In meantime, I started re-writing the documentation (see the README and the source code).
Sorry for the mess.
